#!/bin/bash
COff='\033[0m'             # Text Reset
# Regular Colors
BlackC='\033[0;30m'        # Black
RedC='\033[0;31m'          # Red
GreenC='\033[0;32m'        # Green
YellowC='\033[0;33m'       # Yellow
BlueC='\033[0;34m'         # Blue
PurpleC='\033[0;35m'       # Purple
CyanC='\033[0;36m'         # Cyan
WhiteC='\033[0;37m'        # White
# Bold
BBlackC='\033[1;30m'       # Black
BRedC='\033[1;31m'         # Red
BGreenC='\033[1;32m'       # Green
BYellowC='\033[1;33m'      # Yellow
BBlueC='\033[1;34m'        # Blue
BPurpleC='\033[1;35m'      # Purple
BCyanC='\033[1;36m'        # Cyan
BWhiteC='\033[1;37m'       # White
# Bold High Intensity
BIBlackC='\033[1;90m'      # Black
BIRedC='\033[1;91m'        # Red
BIGreenC='\033[1;92m'      # Green
BIYellowC='\033[1;93m'     # Yellow
BIBlueC='\033[1;94m'       # Blue
BIPurpleC='\033[1;95m'     # Purple
BICyanC='\033[1;96m'       # Cyan
BIWhiteC='\033[1;97m'      # White
# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White
echo -e $BIWhiteC$On_Black"CleanVASPf v.20210208"$COff
rm -f POTCAR out_* OSZICAR *.runjob slurm* OUTCAR.[0-9] OUTCAR.[0-9].gz CONTCAR.[0-9] CHG* DOSCAR IBZKPT PCDAT POTCAR runjob vasp* WAVECAR XDATCAR
pos2xyz.pl CONTCAR
pos2cif.pl CONTCAR
pos2xyz.pl POSCAR
pos2cif.pl POSCAR
if [ -f POSCAR.0 ]; then
   pos2cif.pl POSCAR.0
   pos2xyz.pl POSCAR.0
fi
[[ -f ./OUTCAR ]] && VASPcv OUTCAR
[[ -f ./OUTCAR.gz ]] && VASPcv OUTCAR.gz
[[ ! -f ./OUTCAR.gz ]] && echo -e $RedC
[[ ! -f ./OUTCAR.gz ]] && gzip -v OUTCAR ; echo
echo -e $BlueC"Final content of the folder"
echo -e       "---------------------------"$COff
ls
